{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "1ed88dcd",
   "metadata": {},
   "source": [
    "# How to Persist Conda Environments in the big Pangeo\n",
    "- Big Pangeo == pangeo.chs.usgs.gov\n",
    "\n",
    "## Statement of the problem \n",
    "\n",
    "- when using the big pangeo - how do i get a persistant conda environment\n",
    "- short answer is set it up in your home directory"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9d557a43",
   "metadata": {},
   "source": [
    "# Answer\n",
    "\n",
    "- tried to create a conda env with the latest big pangeo start button - FAIL\n",
    "- reverted to the last version of jupyter hub on the big pangeo --> SUCCESS\n",
    "\n",
    "```\n",
    "conda create --prefix ~/my_condas/maheshv2\n",
    "```\n",
    "\n",
    "> conda activate ~/my_condas/maheshv2\n",
    "\n",
    "convert pangeo_env.yaml to just a text file of libraries 1,$ s/  - //g\n",
    "\n",
    "- conda install -y mamba\n",
    "- mamba install --file pangeo_libaries.txt\n",
    "- wait 30 minutes - then success\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "311fd42c",
   "metadata": {},
   "source": [
    "# Article - Reference\n",
    "\n",
    "- https://towardsdatascience.com/get-your-conda-environment-to-show-in-jupyter-notebooks-the-easy-way-17010b76e874"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "2e7fc731",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "PWD=/home/jovyan/opt/personal-pangeo/bigpangeo\r\n",
      "HOME=/home/jovyan\r\n"
     ]
    }
   ],
   "source": [
    "! env | grep -i home"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "a129de65",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "# conda environments:\r\n",
      "#\r\n",
      "                         /home/jovyan/.envs\r\n",
      "base                     /srv/conda\r\n",
      "pangeo                *  /srv/conda/envs/pangeo\r\n",
      "\r\n"
     ]
    }
   ],
   "source": [
    "! conda env list"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b087d039",
   "metadata": {},
   "source": [
    "# What env am i using?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "1c68e3a6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "pangeo\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "print (os.environ['CONDA_DEFAULT_ENV'])"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "46446661",
   "metadata": {},
   "source": [
    "# Step 1 -- create a place for my custom conda environments - mkdir"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "25c65eb2",
   "metadata": {},
   "outputs": [],
   "source": [
    "! mkdir ~/my_condas"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c06aee09",
   "metadata": {},
   "source": [
    "# Step 2 create a new conda env in this directory"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "4d7670ff",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting package metadata (current_repodata.json): ...working... done\n",
      "Solving environment: ...working... done\n",
      "Collecting package metadata (current_repodata.json): ...working... failed\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<\n",
      "\n",
      "    Traceback (most recent call last):\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/gateways/connection/session.py\", line 60, in __call__\n",
      "        return cls._thread_local.session\n",
      "    AttributeError: '_thread._local' object has no attribute 'session'\n",
      "    \n",
      "    During handling of the above exception, another exception occurred:\n",
      "    \n",
      "    Traceback (most recent call last):\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/exceptions.py\", line 1079, in __call__\n",
      "        return func(*args, **kwargs)\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/cli/main.py\", line 84, in _main\n",
      "        exit_code = do_call(args, p)\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/cli/conda_argparse.py\", line 83, in do_call\n",
      "        return getattr(module, func_name)(args, parser)\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/cli/main_create.py\", line 41, in execute\n",
      "        install(args, parser, 'create')\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/cli/install.py\", line 265, in install\n",
      "        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/core/solve.py\", line 123, in solve_for_transaction\n",
      "        self._notify_conda_outdated(link_precs)\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/core/solve.py\", line 971, in _notify_conda_outdated\n",
      "        repodata_fn=self._repodata_fn),\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/core/subdir_data.py\", line 140, in query_all\n",
      "        result = tuple(concat(executor.map(subdir_query, channel_urls)))\n",
      "      File \"/srv/conda/lib/python3.7/concurrent/futures/_base.py\", line 598, in result_iterator\n",
      "        yield fs.pop().result()\n",
      "      File \"/srv/conda/lib/python3.7/concurrent/futures/_base.py\", line 435, in result\n",
      "        return self.__get_result()\n",
      "      File \"/srv/conda/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "        raise self._exception\n",
      "      File \"/srv/conda/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "        result = self.fn(*self.args, **self.kwargs)\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/core/subdir_data.py\", line 133, in <lambda>\n",
      "        package_ref_or_match_spec))\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/core/subdir_data.py\", line 145, in query\n",
      "        self.load()\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/core/subdir_data.py\", line 209, in load\n",
      "        _internal_state = self._load()\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/core/subdir_data.py\", line 375, in _load\n",
      "        repodata_fn=self.repodata_fn)\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/core/subdir_data.py\", line 680, in fetch_repodata_remote_request\n",
      "        session = CondaSession()\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/gateways/connection/session.py\", line 62, in __call__\n",
      "        session = cls._thread_local.session = super(CondaSessionType, cls).__call__()\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/gateways/connection/session.py\", line 88, in __init__\n",
      "        raise_on_status=False)\n",
      "    TypeError: __init__() got an unexpected keyword argument 'raise_on_status'\n",
      "\n",
      "`$ /srv/conda/condabin/conda create --prefix /home/jovyan/my_condas/landsatv1`\n",
      "\n",
      "  environment variables:\n",
      "                 CIO_TEST=<not set>\n",
      "        CONDA_DEFAULT_ENV=pangeo\n",
      "                CONDA_DIR=/srv/conda\n",
      "                CONDA_EXE=/srv/conda/bin/conda\n",
      "             CONDA_PREFIX=/srv/conda/envs/pangeo\n",
      "    CONDA_PROMPT_MODIFIER=(pangeo)\n",
      "         CONDA_PYTHON_EXE=/srv/conda/bin/python\n",
      "               CONDA_ROOT=/srv/conda\n",
      "              CONDA_SHLVL=1\n",
      "            CONDA_VERSION=4.7.12.1\n",
      "           CURL_CA_BUNDLE=<not set>\n",
      "                     PATH=/srv/conda/envs/pangeo/bin:/srv/conda/condabin:/srv/conda/bin:/usr/loc\n",
      "                          al/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\n",
      "       REQUESTS_CA_BUNDLE=<not set>\n",
      "            SSL_CERT_FILE=<not set>\n",
      "        UDUNITS2_XML_PATH=/srv/conda/envs/pangeo/share/udunits/udunits2.xml\n",
      "\n",
      "     active environment : pangeo\n",
      "    active env location : /srv/conda/envs/pangeo\n",
      "            shell level : 1\n",
      "       user config file : /home/jovyan/.condarc\n",
      " populated config files : /srv/conda/.condarc\n",
      "                          /home/jovyan/.condarc\n",
      "          conda version : 4.10.1\n",
      "    conda-build version : not installed\n",
      "         python version : 3.7.4.final.0\n",
      "       virtual packages : __linux=5.4.176=0\n",
      "                          __glibc=2.27=0\n",
      "                          __unix=0=0\n",
      "                          __archspec=1=x86_64\n",
      "       base environment : /srv/conda  (writable)\n",
      "      conda av data dir : /srv/conda/etc/conda\n",
      "  conda av metadata url : https://repo.anaconda.com/pkgs/main\n",
      "           channel URLs : https://conda.anaconda.org/conda-forge/linux-64\n",
      "                          https://conda.anaconda.org/conda-forge/noarch\n",
      "                          https://repo.anaconda.com/pkgs/main/linux-64\n",
      "                          https://repo.anaconda.com/pkgs/main/noarch\n",
      "                          https://repo.anaconda.com/pkgs/r/linux-64\n",
      "                          https://repo.anaconda.com/pkgs/r/noarch\n",
      "          package cache : /srv/conda/pkgs\n",
      "                          /home/jovyan/.conda/pkgs\n",
      "       envs directories : /srv/conda/envs\n",
      "                          /home/jovyan/.conda/envs\n",
      "               platform : linux-64\n",
      "             user-agent : conda/4.10.1 requests/2.9.1 CPython/3.7.4 Linux/5.4.176-91.338.amzn2.x86_64 ubuntu/18.04.5 glibc/2.27\n",
      "                UID:GID : 1000:0\n",
      "             netrc file : /home/jovyan/.netrc\n",
      "           offline mode : False\n",
      "\n",
      "\n",
      "An unexpected error has occurred. Conda has prepared the above report.\n",
      "\n",
      "\n",
      "CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.\n",
      "To initialize your shell, run\n",
      "\n",
      "    $ conda init <SHELL_NAME>\n",
      "\n",
      "Currently supported shells are:\n",
      "  - bash\n",
      "  - fish\n",
      "  - tcsh\n",
      "  - xonsh\n",
      "  - zsh\n",
      "  - powershell\n",
      "\n",
      "See 'conda init --help' for more information and options.\n",
      "\n",
      "IMPORTANT: You may need to close and restart your shell after running 'conda init'.\n",
      "\n",
      "\n",
      "\n",
      "# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<\n",
      "\n",
      "    Traceback (most recent call last):\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/gateways/connection/session.py\", line 60, in __call__\n",
      "        return cls._thread_local.session\n",
      "    AttributeError: '_thread._local' object has no attribute 'session'\n",
      "    \n",
      "    During handling of the above exception, another exception occurred:\n",
      "    \n",
      "    Traceback (most recent call last):\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/exceptions.py\", line 1079, in __call__\n",
      "        return func(*args, **kwargs)\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/cli/main.py\", line 84, in _main\n",
      "        exit_code = do_call(args, p)\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/cli/conda_argparse.py\", line 83, in do_call\n",
      "        return getattr(module, func_name)(args, parser)\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/cli/main_install.py\", line 20, in execute\n",
      "        install(args, parser, 'install')\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/cli/install.py\", line 265, in install\n",
      "        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/core/solve.py\", line 117, in solve_for_transaction\n",
      "        should_retry_solve)\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/core/solve.py\", line 158, in solve_for_diff\n",
      "        force_remove, should_retry_solve)\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/core/solve.py\", line 262, in solve_final_state\n",
      "        ssc = self._collect_all_metadata(ssc)\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/common/io.py\", line 88, in decorated\n",
      "        return f(*args, **kwds)\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/core/solve.py\", line 425, in _collect_all_metadata\n",
      "        index, r = self._prepare(prepared_specs)\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/core/solve.py\", line 1021, in _prepare\n",
      "        self.subdirs, prepared_specs, self._repodata_fn)\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/core/index.py\", line 289, in get_reduced_index\n",
      "        repodata_fn=repodata_fn)\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/core/subdir_data.py\", line 140, in query_all\n",
      "        result = tuple(concat(executor.map(subdir_query, channel_urls)))\n",
      "      File \"/srv/conda/lib/python3.7/concurrent/futures/_base.py\", line 598, in result_iterator\n",
      "        yield fs.pop().result()\n",
      "      File \"/srv/conda/lib/python3.7/concurrent/futures/_base.py\", line 435, in result\n",
      "        return self.__get_result()\n",
      "      File \"/srv/conda/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "        raise self._exception\n",
      "      File \"/srv/conda/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "        result = self.fn(*self.args, **self.kwargs)\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/core/subdir_data.py\", line 133, in <lambda>\n",
      "        package_ref_or_match_spec))\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/core/subdir_data.py\", line 145, in query\n",
      "        self.load()\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/core/subdir_data.py\", line 209, in load\n",
      "        _internal_state = self._load()\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/core/subdir_data.py\", line 375, in _load\n",
      "        repodata_fn=self.repodata_fn)\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/core/subdir_data.py\", line 680, in fetch_repodata_remote_request\n",
      "        session = CondaSession()\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/gateways/connection/session.py\", line 62, in __call__\n",
      "        session = cls._thread_local.session = super(CondaSessionType, cls).__call__()\n",
      "      File \"/srv/conda/lib/python3.7/site-packages/conda/gateways/connection/session.py\", line 88, in __init__\n",
      "        raise_on_status=False)\n",
      "    TypeError: __init__() got an unexpected keyword argument 'raise_on_status'\n",
      "\n",
      "`$ /srv/conda/condabin/conda install -y rasterio`\n",
      "\n",
      "  environment variables:\n",
      "                 CIO_TEST=<not set>\n",
      "        CONDA_DEFAULT_ENV=pangeo\n",
      "                CONDA_DIR=/srv/conda\n",
      "                CONDA_EXE=/srv/conda/bin/conda\n",
      "             CONDA_PREFIX=/srv/conda/envs/pangeo\n",
      "    CONDA_PROMPT_MODIFIER=(pangeo)\n",
      "         CONDA_PYTHON_EXE=/srv/conda/bin/python\n",
      "               CONDA_ROOT=/srv/conda\n",
      "              CONDA_SHLVL=1\n",
      "            CONDA_VERSION=4.7.12.1\n",
      "           CURL_CA_BUNDLE=<not set>\n",
      "                     PATH=/srv/conda/envs/pangeo/bin:/srv/conda/condabin:/srv/conda/bin:/usr/loc\n",
      "                          al/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\n",
      "       REQUESTS_CA_BUNDLE=<not set>\n",
      "            SSL_CERT_FILE=<not set>\n",
      "        UDUNITS2_XML_PATH=/srv/conda/envs/pangeo/share/udunits/udunits2.xml\n",
      "\n",
      "     active environment : pangeo\n",
      "    active env location : /srv/conda/envs/pangeo\n",
      "            shell level : 1\n",
      "       user config file : /home/jovyan/.condarc\n",
      " populated config files : /srv/conda/.condarc\n",
      "                          /home/jovyan/.condarc\n",
      "          conda version : 4.10.1\n",
      "    conda-build version : not installed\n",
      "         python version : 3.7.4.final.0\n",
      "       virtual packages : __linux=5.4.176=0\n",
      "                          __glibc=2.27=0\n",
      "                          __unix=0=0\n",
      "                          __archspec=1=x86_64\n",
      "       base environment : /srv/conda  (writable)\n",
      "      conda av data dir : /srv/conda/etc/conda\n",
      "  conda av metadata url : https://repo.anaconda.com/pkgs/main\n",
      "           channel URLs : https://conda.anaconda.org/conda-forge/linux-64\n",
      "                          https://conda.anaconda.org/conda-forge/noarch\n",
      "                          https://repo.anaconda.com/pkgs/main/linux-64\n",
      "                          https://repo.anaconda.com/pkgs/main/noarch\n",
      "                          https://repo.anaconda.com/pkgs/r/linux-64\n",
      "                          https://repo.anaconda.com/pkgs/r/noarch\n",
      "          package cache : /srv/conda/pkgs\n",
      "                          /home/jovyan/.conda/pkgs\n",
      "       envs directories : /srv/conda/envs\n",
      "                          /home/jovyan/.conda/envs\n",
      "               platform : linux-64\n",
      "             user-agent : conda/4.10.1 requests/2.9.1 CPython/3.7.4 Linux/5.4.176-91.338.amzn2.x86_64 ubuntu/18.04.5 glibc/2.27\n",
      "                UID:GID : 1000:0\n",
      "             netrc file : /home/jovyan/.netrc\n",
      "           offline mode : False\n",
      "\n",
      "\n",
      "An unexpected error has occurred. Conda has prepared the above report.\n",
      "\n",
      "Upload successful.\n"
     ]
    },
    {
     "ename": "CalledProcessError",
     "evalue": "Command 'b'\\nconda create --prefix ~/my_condas/landsatv1\\nconda activate landsatv1\\nconda install -y rasterio\\n'' returned non-zero exit status 1.",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mCalledProcessError\u001b[0m                        Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-6-6e857b61b1d2>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mget_ipython\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrun_cell_magic\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'bash'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m''\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m'\\nconda create --prefix ~/my_condas/landsatv1\\nconda activate landsatv1\\nconda install -y rasterio\\n'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m/srv/conda/envs/pangeo/lib/python3.7/site-packages/IPython/core/interactiveshell.py\u001b[0m in \u001b[0;36mrun_cell_magic\u001b[0;34m(self, magic_name, line, cell)\u001b[0m\n\u001b[1;32m   2401\u001b[0m             \u001b[0;32mwith\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbuiltin_trap\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   2402\u001b[0m                 \u001b[0margs\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0mmagic_arg_s\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcell\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 2403\u001b[0;31m                 \u001b[0mresult\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mfn\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   2404\u001b[0m             \u001b[0;32mreturn\u001b[0m \u001b[0mresult\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   2405\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/srv/conda/envs/pangeo/lib/python3.7/site-packages/IPython/core/magics/script.py\u001b[0m in \u001b[0;36mnamed_script_magic\u001b[0;34m(line, cell)\u001b[0m\n\u001b[1;32m    140\u001b[0m             \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    141\u001b[0m                 \u001b[0mline\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mscript\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 142\u001b[0;31m             \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mshebang\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mline\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcell\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    143\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    144\u001b[0m         \u001b[0;31m# write a basic docstring:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m<decorator-gen-103>\u001b[0m in \u001b[0;36mshebang\u001b[0;34m(self, line, cell)\u001b[0m\n",
      "\u001b[0;32m/srv/conda/envs/pangeo/lib/python3.7/site-packages/IPython/core/magic.py\u001b[0m in \u001b[0;36m<lambda>\u001b[0;34m(f, *a, **k)\u001b[0m\n\u001b[1;32m    185\u001b[0m     \u001b[0;31m# but it's overkill for just that one bit of state.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    186\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0mmagic_deco\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0marg\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 187\u001b[0;31m         \u001b[0mcall\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mlambda\u001b[0m \u001b[0mf\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m*\u001b[0m\u001b[0ma\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mk\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mf\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0ma\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mk\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    188\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    189\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mcallable\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0marg\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/srv/conda/envs/pangeo/lib/python3.7/site-packages/IPython/core/magics/script.py\u001b[0m in \u001b[0;36mshebang\u001b[0;34m(self, line, cell)\u001b[0m\n\u001b[1;32m    243\u001b[0m             \u001b[0msys\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstderr\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mflush\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    244\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0margs\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mraise_error\u001b[0m \u001b[0;32mand\u001b[0m \u001b[0mp\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mreturncode\u001b[0m\u001b[0;34m!=\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 245\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0mCalledProcessError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mp\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mreturncode\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcell\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0moutput\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mout\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mstderr\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0merr\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    246\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    247\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m_run_script\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mp\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcell\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mto_close\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mCalledProcessError\u001b[0m: Command 'b'\\nconda create --prefix ~/my_condas/landsatv1\\nconda activate landsatv1\\nconda install -y rasterio\\n'' returned non-zero exit status 1."
     ]
    }
   ],
   "source": [
    "%%bash\n",
    "\n",
    "conda create --prefix ~/my_condas/landsatv1\n",
    "conda activate landsatv1\n",
    "conda install -y rasterio"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "da7ca8b5",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:pangeo] *",
   "language": "python",
   "name": "conda-env-pangeo-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
